# Data Merging

<h2>Soal 1: Penggabungan Data</h2>

- Sebutkan perbedaan antara full outer join, inner join, dan left join

Perbedaan utama antara full outer join, inner join, dan left join adalah bagaimana mereka menangani pencocokan baris dari dua tabel.

1. **Inner Join**: Jenis join ini mengembalikan hanya baris yang memiliki nilai yang cocok di kedua tabel. Ini juga dikenal sebagai irisan dari kedua tabel.

2. **Left Join**: Jenis join ini mengembalikan semua baris dari tabel kiri dan baris yang cocok dari tabel kanan. Jika tidak ada baris yang cocok di tabel kanan, kolom dari tabel kanan diisi dengan nilai NULL.

3. **Full Outer Join**: Jenis join ini mengembalikan semua baris dari kedua tabel. Jika tidak ada baris yang cocok di salah satu tabel, kolom dari tabel yang tidak ada diisi dengan nilai NULL.

Secara ringkas, inner join mengembalikan hanya baris yang cocok, left join mengembalikan semua baris dari tabel kiri dan baris yang cocok dari tabel kanan, dan full outer join mengembalikan semua baris dari kedua tabel.

<h2>Soal 2: Penggabungan Data</h2>

Pada quiz no 2 ini gunakan data [names1881.csv](https://drive.google.com/uc?export=download&id=1Pwu3cv93hI79jmi52kJ05xhophknDKat) dan [names1981.csv](https://drive.google.com/uc?export=download&id=1pvsGaybr423hJXcN35e5nS3sg4ha4jo3), data ini berisi nama bayi yang lahir pada tahun 1881 atau 1981 di Amerika.

- Baca data tersebut dengan memberikan nama column 'Name', 'Gender', 'Count'.
- Tunjukan jumlah dimensi dari data 'names1881.csv' dan 'names1981.csv'
- Gabungkan kedua data tersebut berdasarkan sumbu baris
- Tunjukan jumlah dimensi dari data setelah di gabungkan.

In [1]:
import pandas as pd
from google.colab import drive
drive.mount ('/content/gdrive')
# read data

df1 = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/names1881.csv', names=['Name', 'Gender', 'Count'])
df2 = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/names1981.csv', names=['Name', 'Gender', 'Count'])

# periksa dimensi dari kedua data
print("Jumlah Dimensi data 'names1881.csv' :")
print(df1.shape)
print("Jumlah Baris data 'names1981.csv' :")
print(df2.shape)

# gabungkan data
df = pd.concat([df1, df2], ignore_index=True)
print(df)

# periksa dimensi data hasil gabungan
print("Jumlah dimensi data setelah penggabungan : ")
print(df.shape)

Mounted at /content/gdrive
Jumlah Dimensi data 'names1881.csv' :
(1935, 3)
Jumlah Baris data 'names1981.csv' :
(19455, 3)
            Name Gender  Count
0           Mary      F   6919
1           Anna      F   2698
2           Emma      F   2034
3      Elizabeth      F   1852
4       Margaret      F   1658
...          ...    ...    ...
21385   Zeferino      M      5
21386    Zerrick      M      5
21387   Zimbabwe      M      5
21388     Zoltan      M      5
21389     Zuriel      M      5

[21390 rows x 3 columns]
Jumlah dimensi data setelah penggabungan :
(21390, 3)

Expected Result:

Jumlah Dimensi data 'names1881.csv':

(1935, 3)

Jumlah Baris data 'names1981.csv':

(19455, 3)

![alt text](https://drive.google.com/uc?id=1jMCAdLrcJubjufydZBnzdQkYqDS3Klat)

Jumlah dimensi data setelah penggabungan :

(21390, 3)

<h2>Soal 3: Penggabungan Data</h2>

Lakukan jenis penggabungan data full outer join, inner join, left outer join dan right outer join pada kedua data berikut:

In [2]:
import pandas as pd

data1 = {
    'id' : [1, 2, 3, 4],
    'Feature1' : ['a1', 'a2', 'a3', 'a4'],
    'Feature2' : ['b1', 'b2', 'b3', 'b4']
}

data2 = {
    'id' : [3, 4, 5 ,6, 7],
    'Feature3' : ['c1', 'c2', 'c3', 'c4', 'c5']
}

df1= pd.DataFrame(data1)
df2= pd.DataFrame(data2)

print(df1)
print(df2)

   id Feature1 Feature2
0   1       a1       b1
1   2       a2       b2
2   3       a3       b3
3   4       a4       b4
   id Feature3
0   3       c1
1   4       c2
2   5       c3
3   6       c4
4   7       c5

In [3]:
#join data
df_outer_join = df1.merge(df2, how='outer', on='id')
print(df_outer_join)

df_inner_join = df1.merge(df2, how='inner', on='id')
print(df_inner_join)

df_left_join = df1.merge(df2, how='left', on='id')
print(df_left_join)

df_right_join = df1.merge(df2, how='right', on='id')
print(df_right_join)

   id Feature1 Feature2 Feature3
0   1       a1       b1      NaN
1   2       a2       b2      NaN
2   3       a3       b3       c1
3   4       a4       b4       c2
4   5      NaN      NaN       c3
5   6      NaN      NaN       c4
6   7      NaN      NaN       c5
   id Feature1 Feature2 Feature3
0   3       a3       b3       c1
1   4       a4       b4       c2
   id Feature1 Feature2 Feature3
0   1       a1       b1      NaN
1   2       a2       b2      NaN
2   3       a3       b3       c1
3   4       a4       b4       c2
   id Feature1 Feature2 Feature3
0   3       a3       b3       c1
1   4       a4       b4       c2
2   5      NaN      NaN       c3
3   6      NaN      NaN       c4
4   7      NaN      NaN       c5

Expected Result:

![alt text](https://drive.google.com/uc?id=1kUpkzWh3Y-X_1H1QXHiccdHf4YjqXsDu)

![alt text](https://drive.google.com/uc?id=1ojoAC2oX9P3ZHl0lS3RXipd7gShLOmmC)

![alt text](https://drive.google.com/uc?id=12jDnQzIosn6dizVwl2nPMX1IhhyEZ4FA)

![alt text](https://drive.google.com/uc?id=11znqscNsVZ-cHY-PPgoHEBDWyc6XRtAL)

<h2>Soal 4: Penggabungan Data berbeda label column Key</h2>

Lakukan jenis penggabungan inner join untuk 2 data yang memiliki nama column key yang berbeda ini:

In [4]:
data1 = {
    'key_data1' : [1, 2, 3, 4],
    'Feature1' : ['a1', 'a2', 'a3', 'a4'],
    'Feature2' : ['b1', 'b2', 'b3', 'b4']
}

data2 = {
    'key_data2' : [3, 4, 5 ,6, 7],
    'Feature3' : ['c1', 'c2', 'c3', 'c4', 'c5']
}

df1= pd.DataFrame(data1)
df2= pd.DataFrame(data2)

print(df1)
print(df2)

   key_data1 Feature1 Feature2
0          1       a1       b1
1          2       a2       b2
2          3       a3       b3
3          4       a4       b4
   key_data2 Feature3
0          3       c1
1          4       c2
2          5       c3
3          6       c4
4          7       c5

In [5]:
# Gabungkan kedua data tersebut
df_inner_join = df1.merge(df2, left_on='key_data1', right_on='key_data2', how='inner')
print(df_inner_join)

   key_data1 Feature1 Feature2  key_data2 Feature3
0          3       a3       b3          3       c1
1          4       a4       b4          4       c2

Expected Result:

![alt text](https://drive.google.com/uc?id=1uBiVOPnqns4al88FDc0ENIeTzIxP4wxH)



---



---

# Data GroupBy

<b>Note</b>: Pada kuis kali ini kita akan menggunakan data diamonds.csv yang bisa kalian download [disini](https://drive.google.com/uc?export=download&id=1qQiM9utQUThTPq8jk8stPMh_y2zfqYOd). setelah di download, kalian pindahkan data tersebut satu level dengan direktori file notebook ini.

In [2]:
import pandas as pd
from google.colab import drive
drive.mount ('/content/gdrive')
df = pd.read_csv('/content/gdrive/My Drive/Colab Notebooks/diamonds.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)

Mounted at /content/gdrive

In [3]:
df.head()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

Columns Metadata:

carat: berat diamond

cut: kualitas diamond

color: warna diamond

clarity: level kemurnian diamonds

depth: tinggi dari diamond tabel

table: lebar  dari diamond tabel

price: harga diamond ($US)

x: panjang

y: lebar

z: kedalaaman

<h2>Soal 5: Process Grouping</h2>

Jelaskan prosess yang terjadi dalam grouping data menggungkan method <b>groupby()</b> dari pandas.

jawab:

Metode `groupby()` dalam Pandas digunakan untuk mengelompokkan data berdasarkan kolom atau indeks tertentu. Ini mengembalikan objek `DataFrameGroupBy`, yang merupakan kamus di mana kunci-kunci adalah kelompok unik di mana catatan dibagi, dan nilainya adalah objek groupby. Fungsi `groupby()` membagi data menjadi kategori atau kelompok yang berbeda dan menawarkan fleksibilitas untuk menganalisis data dengan menerapkan berbagai metode pada objek groupby.

Berikut adalah penjelasan langkah demi langkah dari proses tersebut:

1. **Membagi data menjadi kelompok**: Metode `groupby()` membagi data menjadi kelompok-kelompok berbeda berdasarkan kolom atau indeks yang ditentukan. Misalnya, jika Anda memiliki DataFrame `df` dan ingin mengelompokkannya berdasarkan kolom 'kategori', Anda dapat menggunakan `df.groupby('kategori')`.

2. **Menerapkan fungsi ke setiap kelompok**: Setelah membagi data menjadi kelompok-kelompok, Anda dapat menerapkan fungsi ke setiap kelompok. Di sinilah fungsi `agg()` berguna. Misalnya, jika Anda ingin menghitung jumlah kolom 'harga' untuk setiap kelompok, Anda dapat menggunakan `df.groupby('kategori').agg(sum)`.

3. **Menggabungkan hasil**: Terakhir, Anda dapat menggabungkan hasil dari aplikasi fungsi untuk mendapatkan output yang diinginkan. Misalnya, jika Anda ingin mendapatkan DataFrame dengan data yang dikelompokkan, Anda dapat menggunakan `df.groupby('kategori').agg(sum).reset_index(name='total_harga')`.

Metode `groupby()` adalah alat yang powerful dalam Pandas yang memungkinkan Anda melakukan berbagai operasi pada data Anda, seperti agregasi, transformasi, dan filtrasi, untuk mendapatkan wawasan dan memahami data Anda lebih baik.

<h2>Soal 6: Grouping All Column</h2>
    
Group data diamond berdasarkan cut (kualitas), lakukan aggregasi dengan fungsi rata2.

In [9]:
#code here
avg_cut=df.groupby('cut').mean(numeric_only=True)
print(avg_cut.head())

              carat      depth      table        price         x         y  \
cut
Fair       1.046137  64.041677  59.053789  4358.757764  6.246894  6.182652
Good       0.849185  62.365879  58.694639  3928.864452  5.838785  5.850744
Ideal      0.702837  61.709401  55.951668  3457.541970  5.507451  5.520080
Premium    0.891955  61.264673  58.746095  4584.257704  5.973887  5.944879
Very Good  0.806381  61.818275  57.956150  3981.759891  5.740696  5.770026

                  z
cut
Fair       3.982770
Good       3.639507
Ideal      3.401448
Premium    3.647124
Very Good  3.559801

Expected Output:

![alt text](https://drive.google.com/uc?id=1GKanuLzNv_pYBFVRBmQywxQw39uQBvSl)

<h2>Soal 7: Grouping Some Column base on Multiple Criteria</h2>
    
Lakukan groupby pada data berdasarkan kriteria cut (kualitas) dan color (warna) secara berurutan, dengan aggregasi pada column carat, table, dan price saja. dengan fungsi agregasi rata-rata.

In [15]:
#code here
grouped_df=df.groupby(['cut', 'color'])
aggregated_df=grouped_df[['carat', 'table', 'price']].mean()
print(aggregated_df.head())

               carat      table        price
cut  color
Fair D      0.920123  58.969325  4291.061350
     E      0.856607  59.364732  3682.312500
     F      0.904712  59.453205  3827.003205
     G      1.023822  58.773248  4239.254777
     H      1.219175  58.696370  5135.683168

Expected Output:

Note: gambar hanya sebagaian dari keseluruhan data

![alt text](https://drive.google.com/uc?id=1XB_uHor7ZCPQUH9uQjSfd6aC6_yJnjh9)

<h2>Soal 8: Group By Multiple Aggregate Base on Multiple Criteria</h2>
    
Lakukan groupby pada data berdasarkan kriteria cut(kualitas) dan color (warna) secara berurutan kemudian aggregasi objek group by nya dengan fungsi rata2 dan median.

In [7]:
#code here
grouped_df=df.groupby(['cut', 'color'])
aggregated_df=grouped_df.agg({'carat':['mean', 'median'], 'depth':['mean', 'median'], 'table':['mean', 'median'], 'price':['mean', 'median'], 'x':['mean', 'median'], 'y':['mean', 'median'], 'z':['mean', 'median']})
print(aggregated_df)

                    carat             depth             table         \
                     mean median       mean median       mean median
cut       color
Fair      D      0.920123  0.900  64.048466   64.8  58.969325   58.0
          E      0.856607  0.900  63.319643   64.8  59.364732   59.0
          F      0.904712  0.900  63.508013   64.8  59.453205   59.0
          G      1.023822  0.980  64.339809   65.0  58.773248   58.0
          H      1.219175  1.010  64.585149   65.1  58.696370   58.0
          I      1.198057  1.010  64.220571   65.1  59.237143   58.0
          J      1.341176  1.030  64.357143   65.0  58.917647   58.0
Good      D      0.744517  0.700  62.365710   63.4  58.541541   58.0
          E      0.745134  0.700  62.203751   63.3  58.779957   58.0
          F      0.775930  0.710  62.202310   63.2  58.910891   59.0
          G      0.850896  0.900  62.526636   63.4  58.471986   58.0
          H      0.914729  0.900  62.499573   63.4  58.611111   58.0
          I      1.057222  1.000  62.475096   63.5  58.773946   58.0
          J      1.099544  1.020  62.395765   63.4  58.813029   58.0
Ideal     D      0.565766  0.500  61.678370   61.8  55.965632   56.0
          E      0.578401  0.500  61.686677   61.8  55.967461   56.0
          F      0.655829  0.530  61.675562   61.8  55.924203   56.0
          G      0.700715  0.540  61.700164   61.8  55.902375   56.0
          H      0.799525  0.700  61.733194   61.8  55.965843   56.0
          I      0.913029  0.740  61.793598   61.9  56.021357   56.0
          J      1.063594  1.030  61.821987   61.9  56.012612   56.0
Premium   D      0.721547  0.580  61.169245   61.3  58.718964   59.0
          E      0.717745  0.580  61.175909   61.3  58.779461   59.0
          F      0.827036  0.760  61.259974   61.5  58.679279   59.0
          G      0.841488  0.755  61.279480   61.4  58.702360   59.0
          H      1.016449  1.010  61.322034   61.5  58.792034   59.0
          I      1.144937  1.140  61.328641   61.6  58.771849   59.0
          J      1.293094  1.250  61.390099   61.6  58.874752   59.0
Very Good D      0.696424  0.610  61.750165   62.2  58.041309   58.0
          E      0.676317  0.570  61.730250   62.0  58.038875   58.0
          F      0.740961  0.700  61.721627   62.0  57.848429   58.0
          G      0.766799  0.700  61.841279   62.1  57.784428   58.0
          H      0.915948  0.900  61.968366   62.3  57.903015   58.0
          I      1.046952  1.005  61.934551   62.2  58.105150   58.0
          J      1.133215  1.060  61.902065   62.2  58.277729   58.0

                       price                 x                y         \
                        mean  median      mean median      mean median
cut       color
Fair      D      4291.061350  3730.0  6.018344  6.080  5.963190  6.010
          E      3682.312500  2956.0  5.909063  6.070  5.858214  6.020
          F      3827.003205  3035.0  5.990513  6.060  5.931122  5.990
          G      4239.254777  3057.0  6.173822  6.125  6.114076  6.040
          H      5135.683168  3816.0  6.579373  6.330  6.497393  6.250
          I      4685.445714  3246.0  6.564457  6.340  6.493486  6.270
          J      4975.655462  3302.0  6.747311  6.490  6.675882  6.460
Good      D      3405.382175  2728.5  5.620076  5.690  5.633897  5.730
          E      3423.644159  2420.0  5.617889  5.680  5.632454  5.710
          F      3495.750275  2647.0  5.693443  5.760  5.709659  5.790
          G      4123.482204  3340.0  5.850264  6.050  5.862824  6.070
          H      4276.254986  3468.5  5.968789  6.110  5.974245  6.130
          I      5078.532567  3639.5  6.253544  6.275  6.260536  6.260
          J      4574.172638  3733.0  6.377003  6.440  6.386026  6.460
Ideal     D      2629.094566  1576.0  5.186704  5.110  5.196224  5.110
          E      2597.550090  1437.0  5.215762  5.100  5.232214  5.110
          F      3374.939362  1775.0  5.408751  5.230  5.422250  5.240
          G      3720.706388  1857.5  5.511214  5.240  5.524007  5.260
          H      3889.334831  2278.0  5.731377  5.680  5.740446  5.710
          I      4451.970377  2659.0  5.976197  5.840  5.989479  5.860
          J      4918.186384  4096.0  6.320045  6.495  6.332098  6.510
Premium   D      3631.292576  2009.0  5.599869  5.380  5.571472  5.340
          E      3538.914420  1928.0  5.587116  5.410  5.558353  5.360
          F      4324.890176  2841.0  5.876692  5.890  5.844655  5.860
          G      4500.742134  2745.0  5.864254  5.900  5.833345  5.870
          H      5216.706780  4511.0  6.244508  6.480  6.228110  6.450
          I      5946.180672  4640.0  6.489531  6.740  6.453270  6.690
          J      6294.591584  5063.0  6.809975  6.920  6.770644  6.900
Very Good D      3470.467284  2310.0  5.501210  5.460  5.531613  5.490
          E      3214.652083  1989.5  5.432467  5.330  5.463213  5.365
          F      3778.820240  2471.0  5.610504  5.690  5.642717  5.720
          G      3872.753806  2437.0  5.660204  5.680  5.688752  5.710
          H      4535.390351  3734.0  5.982286  6.130  6.006272  6.160
          I      5255.879568  3888.0  6.272259  6.350  6.299028  6.360
          J      5103.513274  4113.0  6.460782  6.560  6.495074  6.575

                        z
                     mean median
cut       color
Fair      D      3.839877  3.900
          E      3.722143  3.760
          F      3.787821  3.815
          G      3.963153  3.970
          H      4.219373  4.090
          I      4.193486  4.080
          J      4.319664  4.150
Good      D      3.504864  3.540
          E      3.496066  3.480
          F      3.544609  3.580
          G      3.647922  3.790
          H      3.726937  3.830
          I      3.901513  3.895
          J      3.977459  4.010
Ideal     D      3.201800  3.160
          E      3.220346  3.150
          F      3.338732  3.220
          G      3.403120  3.230
          H      3.539917  3.510
          I      3.695270  3.600
          J      3.912757  4.010
Premium   D      3.415926  3.300
          E      3.408875  3.290
          F      3.588391  3.590
          G      3.579641  3.610
          H      3.811699  3.960
          I      3.963894  4.130
          J      4.168020  4.260
Very Good D      3.405089  3.360
          E      3.373996  3.280
          F      3.472902  3.530
          G      3.509883  3.540
          H      3.713849  3.830
          I      3.890972  3.935
          J      4.006873  4.060

Expected Output:

Note : gambar hanya sebagaian dari keseluruhan data

![alt text](https://drive.google.com/uc?id=1fUPIse5ELrzj26ZyWBqsAVOUb6yf7UoD)

<h2>Soal 9: Group By With Different Aggregation for specific Column</h2>
    
Lakukan groupby pada data berdasarkan criteria cut(kualitas), kemudian aggreagate dengan fungsi max pada column price dan fungsi min pada column carat.

In [9]:
#code here
grouped_df=df.groupby('cut').agg({'price':'max', 'carat':'min'})
print(grouped_df)

           price  carat
cut
Fair       18574   0.22
Good       18788   0.23
Ideal      18806   0.20
Premium    18823   0.20
Very Good  18818   0.20

Expected Output:

![alt text](https://drive.google.com/uc?id=1B_z5PBkLe4hNJJJV3JgDGP9G--llytKf)

<h2>Soal 10: Group By With Custom Function</h2>
    
Lakukan groupby pada data berdasarkan criteria cut(kualitas), kemudian lakukan aggregasi dengan fungsi standar deviasi pada column carat dan fungsi rentang nilai antara max dan min pada column price.

In [13]:
#code here
grouped_df=df.groupby('cut').agg({'carat':'std', 'price':lambda x:x.max()-x.min()})
print(grouped_df)

              carat  price
cut
Fair       0.516404  18237
Good       0.454054  18461
Ideal      0.432876  18480
Premium    0.515262  18497
Very Good  0.459435  18482

Expected Output:

![alt text](https://drive.google.com/uc?id=1bl6_8KryXCxLfzpAf4YF80Qvt15a3uQ6)



---



---