In [ ]:
import pandas as pd
import random

data = {
    'Tipe Ujian' : ['UTS1', 'UAS1', 'UTS2', 'UAS2']*3,
    'Mata Pelajaran' : ['Fisika']*4 + ['Matematika']*4+['Statistika']*4,
    'Rata2 Waktu Belajar (menit)' : [random.choice(range(200, 800)) for i in range(12)],
    'Rata2 Nilai Ujian' : [random.choice(range(40, 100)) for i in range(12)]
}

df = pd.DataFrame(data)
df

   Tipe Ujian Mata Pelajaran  Rata2 Waktu Belajar (menit)  Rata2 Nilai Ujian
0        UTS1         Fisika                          404                 96
1        UAS1         Fisika                          706                 83
2        UTS2         Fisika                          255                 50
3        UAS2         Fisika                          360                 48
4        UTS1     Matematika                          423                 64
5        UAS1     Matematika                          792                 76
6        UTS2     Matematika                          407                 46
7        UAS2     Matematika                          617                 55
8        UTS1     Statistika                          774                 50
9        UAS1     Statistika                          620                 98
10       UTS2     Statistika                          343                 77
11       UAS2     Statistika                          528                 96



---



---

## Soal 1. Data Cleaning

Lakukan sorting data berdasarkan Rata2 nilai ujian dari terbesar ke terkecil

*   Lakukan sorting data berdasarkan Rata2 nilai ujian dari terbesar ke terkecil
*   Tipe Ujian dan Mata pelajaran apakah yang memiliki rata2 nilai terkecil?

In [ ]:
#code here
df_sorted=df.sort_values(by='Rata2 Nilai Ujian', ascending=False, inplace=True)
print(df_sorted)

min_index=df.groupby(['Tipe Ujian', 'Mata Pelajaran'])['Rata2 Nilai Ujian'].idxmin()
min_values=df.loc[min_index]
print(min_values[['Tipe Ujian', 'Mata Pelajaran', 'Rata2 Waktu Belajar (menit)', 'Rata2 Nilai Ujian']])

None
   Tipe Ujian Mata Pelajaran  Rata2 Waktu Belajar (menit)  Rata2 Nilai Ujian
1        UAS1         Fisika                          706                 83
5        UAS1     Matematika                          792                 76
9        UAS1     Statistika                          620                 98
3        UAS2         Fisika                          360                 48
7        UAS2     Matematika                          617                 55
11       UAS2     Statistika                          528                 96
0        UTS1         Fisika                          404                 96
4        UTS1     Matematika                          423                 64
8        UTS1     Statistika                          774                 50
2        UTS2         Fisika                          255                 50
6        UTS2     Matematika                          407                 46
10       UTS2     Statistika                          343                 77

Expected output:

(Output bisa berbeda-beda)

![alt text](https://drive.google.com/uc?id=1iv8P-LDdN3WpTVX9qST3kL7QSNSDiOc2)



---



---

<h2>Soal 2: Data Restructuring</h2>

Jelaskan itu pivoting dan melting data

<h3><b>Pivoting</b></h3>

Pivoting adalah operasi transformasi data yang dilakukan menggunakan fungsi `pivot()` dalam perpustakaan Pandas. Pivoting digunakan untuk mengubah bentuk data dari format yang lebar menjadi format yang sempit, di mana baris menjadi kolom dan kolom menjadi baris. Transformasi ini sangat berguna ketika Anda ingin membandingkan berbagai variabel di seluruh entitas dengan lebih efektif.

Fungsi `pivot()` dalam Pandas memungkinkan Anda untuk menentukan indeks, kolom, dan nilai yang akan digunakan dalam DataFrame baru. Parameter indeks menetapkan struktur baris dari DataFrame baru, parameter kolom mengidentifikasi nilai unik mana yang akan berfungsi sebagai kolom baru, dan parameter nilai memastikan bahwa data yang tepat masuk ke dalam struktur baru.

Berikut adalah contoh penggunaan fungsi `pivot()`:

```python
import pandas as pd

df=pd.DataFrame({'A': ['John', 'Boby', 'Mina'], 'B': ['Masters', 'Graduate', 'Graduate'], 'C': [27, 23, 21]})

pivoted_df=df.pivot('A', 'B', 'C')

print(pivoted_df)
```

Ini akan menghasilkan DataFrame yang dipivot di mana 'A' menjadi indeks, 'B' menjadi kolom, dan nilai-nilai di kolom 'C' mengisi sel-sel tabel pivot yang dihasilkan. Fungsi ini mengasumsikan bahwa setiap kombinasi 'A' dan 'B' memiliki nilai yang sesuai yang unik di 'C'.

Pivoting adalah keterampilan penting untuk manipulasi, transformasi, dan analisis data dalam Python. Ini membantu menjaga integritas data dengan menghindari duplikasi yang tidak perlu, meningkatkan analisis data dengan menyusun ulang kumpulan data, dan meningkatkan visualisasi data dengan mengatur data dengan cara yang dapat dengan mudah diinterpretasikan dan memberikan wawasan yang jelas tentang pola dan tren yang mendasarinya.

<h3><b>Melting Data</b></h3>

Melting data merujuk pada proses mengubah bentuk DataFrame dari format yang lebar menjadi format yang panjang menggunakan fungsi `melt()` dalam perpustakaan Pandas. Fungsi `melt()` digunakan untuk mentransformasikan DataFrame di mana satu atau lebih kolom adalah variabel identifikasi (id_vars), sementara semua kolom lainnya, yang dianggap sebagai variabel yang diukur (value_vars), "dipivot" ke sumbu baris, meninggalkan hanya dua kolom non-identifikasi, 'variable' dan 'value'.

Tujuan utama dari melting data adalah untuk mengorganisir data dalam format yang lebih ramah komputer yang lebih mudah untuk dianalisis dan divisualisasikan. Transformasi ini sangat berguna ketika Anda memiliki DataFrame dengan format yang lebar dengan beberapa kolom dan ingin mengonversinya menjadi format yang panjang dengan satu baris untuk setiap pengamatan.

Berikut adalah contoh penggunaan fungsi `melt()`:

```python
import pandas as pd

df = pd.DataFrame({'A': ['John', 'Boby', 'Mina'], 'B': ['Masters', 'Graduate', 'Graduate'], 'C': [27, 23, 21]})

melted_df = pd.melt(df, id_vars=['A'], value_vars=['B'])

print(melted_df)
```

Ini akan menghasilkan DataFrame yang melted di mana 'A' menjadi indeks, 'B' menjadi kolom, dan nilai-nilai di kolom 'C' mengisi sel-sel tabel pivot yang dihasilkan. Fungsi ini mengasumsikan bahwa setiap kombinasi 'A' dan 'B' memiliki nilai yang sesuai yang unik di 'C'.

Melting data adalah keterampilan penting untuk manipulasi, transformasi, dan analisis data dalam Python. Ini membantu menjaga integritas data dengan menghindari duplikasi yang tidak perlu, meningkatkan analisis data dengan menyusun ulang kumpulan data, dan meningkatkan visualisasi data dengan mengatur data dengan cara yang dapat dengan mudah diinterpretasikan dan memberikan wawasan yang jelas tentang pola dan tren yang mendasarinya.



---



---

<h2>Soal 3: Reshaping Data 1</h2>

In [ ]:
import pandas as pd
import random

data = {
    'Tipe Ujian' : ['UTS1', 'UAS1', 'UTS2', 'UAS2']*3,
    'Mata Pelajaran' : ['Fisika']*4 + ['Matematika']*4+['Statistika']*4,
    'Rata2 Waktu Belajar (menit)' : [random.choice(range(200, 800)) for i in range(12)],
    'Rata2 Nilai Ujian' : [random.choice(range(40, 100)) for i in range(12)]
}

df = pd.DataFrame(data)
df

   Tipe Ujian Mata Pelajaran  Rata2 Waktu Belajar (menit)  Rata2 Nilai Ujian
0        UTS1         Fisika                          212                 86
1        UAS1         Fisika                          735                 85
2        UTS2         Fisika                          323                 69
3        UAS2         Fisika                          476                 74
4        UTS1     Matematika                          274                 71
5        UAS1     Matematika                          395                 51
6        UTS2     Matematika                          758                 49
7        UAS2     Matematika                          362                 41
8        UTS1     Statistika                          574                 76
9        UAS1     Statistika                          406                 63
10       UTS2     Statistika                          250                 50
11       UAS2     Statistika                          574                 46

Perhatikan data di atas, kemudian ubahlah bentuknya agar sesuai yang di harapkan.

In [ ]:
#code here
pivot_df=df.pivot_table(index='Tipe Ujian', columns='Mata Pelajaran', values=["Rata2 Nilai Ujian", "Rata2 Waktu Belajar (menit)"])
pivot_df=pivot_df[["Rata2 Nilai Ujian", "Rata2 Waktu Belajar (menit)"]]

print(pivot_df.to_string())

               Rata2 Nilai Ujian                       Rata2 Waktu Belajar (menit)
Mata Pelajaran            Fisika Matematika Statistika                      Fisika Matematika Statistika
Tipe Ujian
UAS1                          45         95         87                         606        232        260
UAS2                          99         41         82                         611        681        388
UTS1                          91         69         56                         639        439        560
UTS2                          61         60         96                         655        278        630

Expected Result:

(Output bisa berbeda-beda)

![alt text](https://drive.google.com/uc?id=1XufsfqZe7-XZLsb92SpATexy-QRZE0ow)



---



---

<h2>Soal 4: Reshaping Data 2</h2>

In [ ]:
import pandas as pd

data = {
    'Hari' : ['Sabtu', 'Minggu'],
    'Kebun Binatang' : [271, 399],
    'Dufan' : [501, 700],
    'Disney' : [1000, 1001],
    'Bali' : [900, 803]
}
df = pd.DataFrame(data).set_index('Hari')
df

        Kebun Binatang  Dufan  Disney  Bali
Hari
Sabtu              271    501    1000   900
Minggu             399    700    1001   803

diatas adalah data tentang jumlah pengunjung di berbagai tempat hiburan, ubahlah struktur data tersebut sehingga sesuai dengan hasil yang diharapkan.

In [ ]:
#code here
melted_df=df.reset_index().melt(id_vars=['Hari'], var_name='Tempat Hiburan', value_name='Pengunjung')
print(melted_df)

     Hari  Tempat Hiburan  Pengunjung
0   Sabtu  Kebun Binatang         271
1  Minggu  Kebun Binatang         399
2   Sabtu           Dufan         501
3  Minggu           Dufan         700
4   Sabtu          Disney        1000
5  Minggu          Disney        1001
6   Sabtu            Bali         900
7  Minggu            Bali         803

Expected Result:

(Output bisa berbeda-beda)

![alt text](https://drive.google.com/uc?id=159mIqcyfeD30EEcyZmmkovORa6cZDLtn)



---



---

<h2>Soal 5: Data Enrichment</h2>

Lakukan binning data menggunakan qcut sehingga sesuai hasil yang diharapkan

In [ ]:
#code here
bins=[0, df['Rata2 Waktu Belajar (menit)'].quantile(0.25), df['Rata2 Waktu Belajar (menit)'].quantile(0.75), float('inf')]
labels=['tidak lulus', 'remedial', 'lulus']

df['Keterangan kelulusan'] = pd.qcut(df['Rata2 Waktu Belajar (menit)'], q=[0, 0.25, 0.75, 1], labels=labels)

print(df)

   Tipe Ujian Mata Pelajaran  Rata2 Waktu Belajar (menit)  Rata2 Nilai Ujian  \
0        UTS1         Fisika                          212                 86
1        UAS1         Fisika                          735                 85
2        UTS2         Fisika                          323                 69
3        UAS2         Fisika                          476                 74
4        UTS1     Matematika                          274                 71
5        UAS1     Matematika                          395                 51
6        UTS2     Matematika                          758                 49
7        UAS2     Matematika                          362                 41
8        UTS1     Statistika                          574                 76
9        UAS1     Statistika                          406                 63
10       UTS2     Statistika                          250                 50
11       UAS2     Statistika                          574                 46

   Keterangan kelulusan
0           tidak lulus
1                 lulus
2              remedial
3              remedial
4           tidak lulus
5              remedial
6                 lulus
7              remedial
8              remedial
9              remedial
10          tidak lulus
11             remedial

Expected Output:

(Output bisa berbeda-beda)

![alt text](https://drive.google.com/uc?id=1h2_u5_xhD1_QtPpItTj-o3lljHhnr4XS)



---



---